trigger:
  - main  # Trigger the pipeline on commits to the 'main' branch

pool:
  name: MySelfHostedPool  # Your self-hosted agent pool

variables:
  imageName: 'test-api1'  # Docker image name
  acrLoginServer: 'acrallnew.azurecr.io'  # ACR login server URL (if you use Azure ACR, otherwise ignore)
  tag: '$(Build.BuildId)'  # Image tag based on build ID
  azureSubscription: 'sc-new'  # Your Azure service connection name
  acrName: 'acrallnew'  # ACR name (if you use Azure ACR, otherwise ignore)
  resourceGroup: 'devops-connection'  # Resource group where AKS is located
  aksCluster: 'aks-all'  # AKS cluster name
  containerRegistry: 'dsc'  # Docker Hub service connection name
  dockerfilePath: './Dockerfile'  # Path to your Dockerfile
  kubernetesNamespace: 'default'  # Kubernetes namespace for deployment
  deploymentFile: 'deployment.yaml'  # Path to your Kubernetes deployment YAML file
  mavenOptions: '-DskipTests'  # Maven options (skip tests for faster builds, adjust as needed)

steps:

# Step 1: Checkout code from GitHub repository
- task: Checkout@1
  displayName: 'Checkout Code'
  inputs:
    repository: 'https://github.com/snagappagari/test-api1.git'
    ref: 'refs/heads/main'

# Step 2: Build the project using Maven
- task: Maven@3
  displayName: 'Build the project with Maven'
  inputs:
    mavenPomFile: 'pom.xml'  # Path to the Maven `pom.xml` file
    goals: 'clean package $(mavenOptions)'  # Clean and package the project
    options: '-DskipTests'  # Optionally skip tests to speed up the build

# Step 3: Authenticate to Docker Hub using service connection 'dsc'
- task: Docker@2
  displayName: 'Authenticate to Docker Hub'
  inputs:
    command: 'login'
    containerRegistry: 'dsc'  # Docker Hub service connection 'dsc'

# Step 4: Build and push Docker image with multi-platform support (amd64 and arm64)
- script: |
    docker buildx create --use || true  # Create and use a builder instance if not already available
    docker buildx build --platform linux/amd64,linux/arm64 \
      -t $(acrLoginServer)/$(imageName):$(tag) \
      -t $(acrLoginServer)/$(imageName):latest \
      --push .  # Push images to Docker Hub
  displayName: 'Build and push multi-platform Docker image to Docker Hub'

# Step 5: Get AKS credentials and configure kubectl
- task: AzureCLI@2
  displayName: 'Get AKS Credentials'
  inputs:
    azureSubscription: $(azureSubscription)  # Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster)
    displayName: 'Get AKS credentials'

# Step 6: Deploy to Kubernetes (AKS)
- task: Kubernetes@1
  displayName: 'Deploy to Kubernetes (AKS)'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: $(azureSubscription)  # Azure service connection
    azureResourceGroup: $(resourceGroup)  # Resource group
    kubernetesCluster: $(aksCluster)  # AKS cluster name
    namespace: $(kubernetesNamespace)  # Kubernetes namespace
    command: 'apply'
    arguments:
