apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api1-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api1
  template:
    metadata:
      labels:
        app: test-api1
    spec:
      containers:
      - name: test-api1
        image: acrallnew.azurecr.io/test-api1:${BUILD_ID}  # Use an env-style placeholder
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: test-api1-service
  namespace: default
spec:
  selector:
    app: test-api1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
